FROM node:alpine AS builder

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json package-lock.json /usr/src/app/
RUN npm ci

# Bundle app source
COPY . /usr/src/app

RUN npm run build

FROM nginx AS server

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY start-nginx.sh nginx.conf /
CMD ["bash", "/start-nginx.sh"]
