version: '2'

services:
  db-test:
    environment:
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
    image: postgres:10.3
    ports:
      - 54320:5432
    volumes:
      - dbdata-test:/var/lib/postgresql/data

volumes:
  dbdata-test:
